### ISSUE TITLE
C4model_knownchi.R missing

### ISSUE THREAD

**Issue by rmcnellis** [efwaring/NutNetPhys#4]
The function file "C4model_knownchi.R" is missing from Analysis/C4model, causing an error in calling the function in narea_analysis R script.

**Comment by SmithEcophysLab** [comment]
Risa, please check now. It was added a submodule which does not sync. I believe I have fixed it

**Comment by rmcnellis** [comment]
That fixed it, thanks!

**Comment by rmcnellis** [comment]
Liz,

That fixed it, thanks!

Risa


--

Risa McNellis

Smith Lab, Texas Tech University

***@***.***

________________________________
